sudo: false
addons:
  apt_packages:
  - lib32stdc++6
env:
- SMVERSION=1.9
- SMVERSION=1.10
install:
- wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
- tar -xzf $(cat sourcemod-latest-linux)
before_script:
- cd addons/sourcemod/scripting/
- git clone https://github.com/Franc1sco/sm-zombiereloaded-3-Franug-Edition.git zrsrc
- rm -r ./zrsrc/src/testsuite/
- cp -rl ./zrsrc/src/include/ ./
- mv ./zrsrc/src/zr/ ./
- rm -rf ./zrsrc/
- chmod +x spcomp
- mkdir compiled compiled/zrleader
script: "./compile.sh leader2.sp"
before_deploy:
- cd compiled/zrleader
- cd ../../../
- mkdir zrLeader zrLeader/addons zrLeader/addons/sourcemod zrLeader/addons/sourcemod/configs
  zrLeader/addons/sourcemod/scripting zrLeader/addons/sourcemod/scripting/include
- mv scripting/leader2.sp zrLeader/addons/sourcemod/scripting/
- mv scripting/compiled zrLeader/addons/sourcemod/plugins
- mv scripting/include/* zrLeader/addons/sourcemod/scripting/include/
- mv ../../materials zrLeader/
- zip -rq zrLeader zrLeader
- tar -czf zrLeader.tar.gz zrLeader
deploy:
  provider: releases
  api_key:
    secure: GcaTebUmAIjTkvogTMrBUhZAAje22BffkecVaZAxA1PqV1jvOY7uR7fusadlfNUIyoFefgv4n8/kV75tf1wlD+vHg6Nj8/Jr7/Z3b+GDCAsRTAOCHZapG9Ye7MQ9LZ7FhobPYIQYQ+SMuHYN4YQW6nvxLNiYXdMNkr5Ic1czS59FCCgz/fZJ2G8InnwVUXdTx0VZeY5x+R0oLofP+yRkhjyDC06z/c4DTR42U64XxFN+pHlA76s07yfq6rzaK4AStby4HyglqQUwR2lv629oerOhfozJWeWmEluC3Gf/ODXJ+dRlY3doWID97GYLaaESckEHQjdf+w1hCUgXlTJWQKV1jeEPu9+rtEovUZ8vvfWBOYsJr/ONMLO+/hg//+XzUohb8bk5MEbEE3ej+UjhAe2dMdxU9mxPe9F6j6G2uTsuHcN0fMCQTHFJwWU7mguFyueeZBjfH+IIQBZ07sYn4bfwSPLjk07SNF41s5lvvZ1QfOQx8rfJQCkfE7PD7A/ilClVNLvc1tr8bcZxdI1BKTtKBDKevbnqPzXiQ77nLIqhBl5a0A0hFDuZSBXBpFKeiE+/xqD5R6bhyv69HwsNM5mfjhK6lwYNc1rRIUeQr3YeSR4vB3MeRGbY+FXOSin2ykPFbkqE09ARH1IpQjgCycePH1pER8/m0lQ5Tt17uyM=
  file: 
    - zrLeader.zip
    - zrLeader.tar.gz
    - zrLeader/addons/sourcemod/plugins/leader2.smx
    - zrLeader/addons/sourcemod/scripting/leader2.sp
  on:
    repo: Locomotivers/zrLeader
    branch: master
