sudo: false
addons:
  apt_packages:
  - lib32stdc++6
env:
- SMVERSION=1.9
- SMVERSION=1.10
install:
- wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
- tar -xzf $(cat sourcemod-latest-linux)
before_script:
- cd addons/sourcemod/scripting/
- git clone https://github.com/Franc1sco/sm-zombiereloaded-3-Franug-Edition.git zrsrc
- rm -r ./zrsrc/src/testsuite/
- cp -rl ./zrsrc/src/include/ ./
- mv ./zrsrc/src/zr/ ./
- rm -rf ./zrsrc/
- chmod +x spcomp
- mkdir compiled compiled/zrleader
script: "./compile.sh leader2.sp"
before_deploy:
- cd compiled/zrleader
- cd ../../../
- mkdir zrLeader zrLeader/addons zrLeader/addons/sourcemod zrLeader/addons/sourcemod/configs
  zrLeader/addons/sourcemod/scripting zrLeader/addons/sourcemod/scripting/include
- mv scripting/leader2.sp zrLeader/addons/sourcemod/scripting/
- mv scripting/compiled zrLeader/addons/sourcemod/plugins
- mv scripting/include/* zrLeader/addons/sourcemod/scripting/include/
- mv ../../materials zrLeader/
- zip -rq zrLeader zrLeader
- tar -czf zrLeader.tar.gz zrLeader
deploy:
  provider: releases
  api_key:
    secure: Rb92eFJkiElPIo4pt8MIVvYPABDV02dGVpRQ6OZPZdaVaMBqOxXKZfEAEsQ+EvWNTX4IFsNzkFADO+QPxAMXCKODdGT9xuhR2M2fgwGA+JoeU/cbNO6II5f4YJ6QYL2fV3MHdXaBzP8wBqgt0Ytbbt8kTO4H28JEBCmKOKgUEdHYoUhR6R1zHlNrc1NQC9Oui/1X46mGFrH7JzpAw6y3ZPx88rANhlUTFGwz/3nuUbJ3AT5/Sg6d9USJPZGfzZi3Zr14UWizMxTp59pvVurvBts8fBJr6bjM3x6cUz4C1sEYD71D//e3z5DwfmmA84+QWg6X3MqjITVKiAp1NVJRnIbYMt/EJ2ZvaB8j0I778h3RqVo8jyi2PZ/v1x4UONpNX1Dhss35Ga1CsekfS+/x8RPW2URPvaVXYXbIjJH8I+b0fP3mvOly00nvjl2dx/0xNLS+UtFKLfzwv95HpuuWTUUIFXcJWTfPrOdecYsmsgYgZN/HfWiVYBPA33/5AjZheclekM9srwbyvZjpcfztGPIa2CODftNOuoG2AhM5F8Nk8luarFehuBGRfKkjHNdeA2CmrelBfC4tL70ouJm/BmAiBb+lxRDxPrOvidwpbJs5PQ3/LTHJZQcPfeCNEykR21poI3yXnboPZWsl1QPFGsBoTFhbqBNHxCpTZQsGd88=
  file: 
    - zrLeader.zip
    - zrLeader.tar.gz
    - zrLeader/addons/sourcemod/plugins/leader2.smx
    - zrLeader/addons/sourcemod/scripting/leader2.sp
  on:
    repo: Locomotivers/zrLeader
